# Generated by Django 2.2.24 on 2024-03-04 18:02

from django.db import migrations


def fill_new_bulding_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year > 2015:
            Flat.objects.update_or_create(id=flat.id, defaults={'new_building': True})
        else:
            Flat.objects.update_or_create(id=flat.id, defaults={'new_building': False})


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_bulding_field)
    ]
