# Generated by Django 2.2.24 on 2024-03-07 23:47

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parse_phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        pure_phone = phonenumbers.format_number(
            parse_phone_number,
            phonenumbers.PhoneNumberFormat.E164
        )
        Flat.objects.update_or_create(id=flat.id, defaults={'owner_pure_phone': pure_phone})


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number)
    ]
