# Generated by Django 2.2.24 on 2024-03-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240309_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(db_index=True, null=True, related_name='flat_owners', to='property.Flat', verbose_name='Квартиры в собствености'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
