# Generated by Django 2.2.24 on 2024-03-09 21:36

from django.db import migrations


def bind_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    if owners.exists():
        for owner in owners.iterator():
            owner_flats = Flat.objects.filter(owner=owner.owners_name)
            owner.flat.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20240310_0035'),
    ]

    operations = [
        migrations.RunPython(bind_flats_to_owners)
    ]
