# Generated by Django 2.2.24 on 2024-03-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
